### PR TITLE
Updating ganache-cli

### LINKED ISSUE #324: An in-range update of ganache-cli is breaking the build 🚨
## The devDependency [ganache-cli](https://github.com/trufflesuite/ganache-cli) was updated from `6.4.2` to `6.4.3`.

🚨 [View failing branch](https://github.com/tasitlabs/TasitSDK/compare/develop...tasitlabs:greenkeeper%2Fganache-cli-6.4.3).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

ganache-cli is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **ci/circleci: build:** Your tests failed on CircleCI ([Details](https://circleci.com/gh/tasitlabs/TasitSDK/479?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 4 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/commit/c75a27ed24e313aacf31fb5cc5afffce6e95c3ad"><code>c75a27e</code></a> <code>6.4.3</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/commit/b38ffc75f518191c04cb52b9a54001250a4c1004"><code>b38ffc7</code></a> <code>Update ganache-core to v2.5.5</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/commit/4bc3901b4dfb9c0f0865d3a54bb808ae0c58941b"><code>4bc3901</code></a> <code>6.4.3-beta.0</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/commit/78136f3b02b9c855e5e4832162368551762413e3"><code>78136f3</code></a> <code>Update ganache-core to v2.5.5-beta.0</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/compare/1ebd8a8c0771e659691c809d8b41ecab2d437e38...c75a27ed24e313aacf31fb5cc5afffce6e95c3ad">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by marcelomorgado**
### Issue link

#324 

### Auto-close the issue?

Closes #324 

### Types of changes

Technical debt (a code change that doesn't fix a bug or add a feature but makes something clearer for devs)

### Notes

Note

Since `ganache-cli` 6.4.2, some tests are failing because of the `--noVMErrorsOnRPCResponse` option.
An example: 

```javascript

      it("on action error", async () => {
        const errorListener = sinon.fake();

        sampleContract.on("error", errorListener);

        action = sampleContract.revertWrite("some string");
        await action.waitForNonceToUpdate();

        expect(errorListener.callCount).to.equal(1);
      });
```

It's occurring because our error listener is being triggered by the RPC error.
Is interesting why the test is passing until v6.4.1
Extracted to: https://github.com/tasitlabs/TasitSDK/issues/343

### CODE REVIEW

**Comment by pcowgill** [comment]
Hmm, interesting finding!

**Comment by pcowgill** [comment]
@marcelomorgado Darn, merge conflicts again. package-lock.json is pretty prone to that

**Comment by marcelomorgado** [comment]
> @marcelomorgado Darn, merge conflicts again. package-lock.json is pretty prone to that

Done

**Comment by pcowgill** [comment]
@marcelomorgado Hmm, 0 changed files in this PR

**Comment by marcelomorgado** [comment]
Weird, on `develop`:

> "ganache-cli": "^6.4.0",

in this branch:

> "ganache-cli": "6.4.1",

**Comment by marcelomorgado** [comment]
> Weird, on `develop`:
> 
> > "ganache-cli": "^6.4.0",
> 
> in this branch:
> 
> > "ganache-cli": "6.4.1",

I've created another PR: https://github.com/tasitlabs/TasitSDK/pull/346

**Pull request closed without merging**
