### PR TITLE
Log ganache-cli output

### PR DESCRIPTION
**Pull request by pcowgill**
### Issue link

https://github.com/tasitlabs/TasitSDK/pull/386#discussion_r282224108

### Types of changes

Technical debt (a code change that doesn't fix a bug or add a feature but makes something clearer for devs)

### Notes

Still TBD how to have a version of ganache running that logs thing but still lets us automatically run migrations after that has been done for a single `npm start` command for local development

### CODE REVIEW

**Comment by marcelomorgado** [comment]
We can pipe the `ganache-cli` process to a log file (ignored by git) instead of `/dev/null`. Make sense?

**Comment by pcowgill** [comment]
> We can pipe the `ganache-cli` process to a log file (ignored by git) instead of `/dev/null`. Make sense?

Yeah, that's a good idea. And then the idea is you would do a `tail -f` for that file in another tab?

**Comment by marcelomorgado** [comment]
> > We can pipe the `ganache-cli` process to a log file (ignored by git) instead of `/dev/null`. Make sense?
> 
> Yeah, that's a good idea. And then the idea is you would do a `tail -f` for that file in another tab?

Exactly.

**Comment by marcelomorgado** [comment]
I'm not sure about `ganache-cli` `-v` option since that log too much, the user could add that if he wants.
With piping to a log, we can stay with existent scripts.

**Comment by pcowgill** [comment]
> I'm not sure about `ganache-cli` `-v` option since that log too much, the user could add that if he wants.

Yeah, now that I've tried it locally I can see that that's definitely too much info

> With piping to a log, we can stay with existent scripts.

Yep, that's better.

**Comment by marcelomorgado** [comment]
I've updated the PR adding the reference of the open thread that requested the comment change.

**Pull request merged**
