### PR TITLE
CircleCI config fixes

### PR DESCRIPTION
**Pull request by pcowgill**
### Issue link

https://github.com/tasitlabs/TasitSDK/issues/74

### Types of changes

Bug fix (non-breaking change that fixes an issue)

Meta (a change that affects future changes to this repo)

Technical debt (a code change that doesn't fix a bug or add a feature but makes something clearer for devs)

### CODE REVIEW

**Comment by pcowgill** [comment]
@marcelomorgado Can you take a look at this? I'm getting this error: `Error: Cannot find module 'strip-ansi'`

https://circleci.com/gh/tasitlabs/TasitSDK/7

**Comment by pcowgill** [comment]
@marcelomorgado FYI I reopened this because I think we still want some of the changes from this PR - your PR was set to auto-close this one (which may or may not have been intentional?).

**Comment by marcelomorgado** [comment]
> @marcelomorgado FYI I reopened this because I think we still want some of the changes from this PR - your PR was set to auto-close this one (which may or may not have been intentional?).

I've tought that only image node version will solve the problem. I've should use refs instead closes. Sorry, I'll work on that using my branch + circle ci.

**Comment by pcowgill** [comment]
No worries! I think the node version did solve the main problem, but all of the the changes here are either syntax improvements for yaml or leverage lerna better, so we might as well have them too. Thanks!

**Pull request merged**
