### PR TITLE
Updating ganache-cli

### LINKED ISSUE #324: An in-range update of ganache-cli is breaking the build 🚨
## The devDependency [ganache-cli](https://github.com/trufflesuite/ganache-cli) was updated from `6.4.2` to `6.4.3`.

🚨 [View failing branch](https://github.com/tasitlabs/TasitSDK/compare/develop...tasitlabs:greenkeeper%2Fganache-cli-6.4.3).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

ganache-cli is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **ci/circleci: build:** Your tests failed on CircleCI ([Details](https://circleci.com/gh/tasitlabs/TasitSDK/479?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 4 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/commit/c75a27ed24e313aacf31fb5cc5afffce6e95c3ad"><code>c75a27e</code></a> <code>6.4.3</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/commit/b38ffc75f518191c04cb52b9a54001250a4c1004"><code>b38ffc7</code></a> <code>Update ganache-core to v2.5.5</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/commit/4bc3901b4dfb9c0f0865d3a54bb808ae0c58941b"><code>4bc3901</code></a> <code>6.4.3-beta.0</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/commit/78136f3b02b9c855e5e4832162368551762413e3"><code>78136f3</code></a> <code>Update ganache-core to v2.5.5-beta.0</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/compare/1ebd8a8c0771e659691c809d8b41ecab2d437e38...c75a27ed24e313aacf31fb5cc5afffce6e95c3ad">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by marcelomorgado**
### Issue link

#324 

### Auto-close the issue?

Closes #324 

### Types of changes

Technical debt (a code change that doesn't fix a bug or add a feature but makes something clearer for devs)

### CODE REVIEW

**Comment by pcowgill** [comment]
`package-lock.json` is unchanged in this version of the PR, but we can always update that later

**Comment by marcelomorgado** [comment]
> `package-lock.json` is unchanged in this version of the PR, but we can always update that later

Seems we are using ganache 6.4.1 seems March 5th (https://github.com/tasitlabs/TasitSDK/commit/902778f31dd1451ea8df3956988c05e906a9bea7#diff-32607347f8126e6534ebc7ebaec4853d)

**Comment by pcowgill** [comment]
You’re looking package-lock.json, right? In that case, maybe it was due to updating truffle and it’s a peer dep

**Comment by marcelomorgado** [comment]
Are you sure? The `tasit-contracts` has it owns `package-lock.json`. I think that when I've updated the package,json with `ganache-cli` 6.4.0 the `ganache-cli` 6.4.1 was already released (03/02) and it is the one installed when I've run `npm install` (since the version on package.json is "^6.4.0". Make sense?

**Comment by pcowgill** [comment]
> Are you sure? The `tasit-contracts` has it owns `package-lock.json`. I think that when I've updated the package,json with `ganache-cli` 6.4.0 the `ganache-cli` 6.4.1 was already released (03/02) and it is the one installed when I've run `npm install` (since the version on package.json is "^6.4.0". Make sense?

Yeah that makes sense - you're probably right about this.

**Pull request merged**
