### PR TITLE
Updating prettier

### LINKED ISSUE #323: An in-range update of prettier is breaking the build 🚨
## The devDependency [prettier](https://github.com/prettier/prettier) was updated from `1.16.4` to `1.17.0`.

🚨 [View failing branch](https://github.com/tasitlabs/TasitSDK/compare/develop...tasitlabs:greenkeeper%2Fprettier-1.17.0).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

prettier is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **ci/circleci: build:** Your tests failed on CircleCI ([Details](https://circleci.com/gh/tasitlabs/TasitSDK/477?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)).
</details>

---

<details>
<summary>Release Notes for Prettier 1.17: More quotes options and support for shared configs</summary>

<p><g-emoji class="g-emoji" alias="link" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f517.png">🔗</g-emoji> <a href="https://prettier.io/blog/2019/04/12/1.17.0.html" rel="nofollow">Release Notes</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by marcelomorgado**
### Issue link

#323 
### Auto-close the issue?

Closes #323 

### Types of changes

Technical debt (a code change that doesn't fix a bug or add a feature but makes something clearer for devs)

### CODE REVIEW

**Comment by pcowgill** [comment]
@marcelomorgado Merge conflicts in this one (likely just a new npm i required)

**Comment by marcelomorgado** [comment]
> @marcelomorgado Merge conflicts in this one (likely just a new npm i required)

Done

**Comment by pcowgill** [comment]
@marcelomorgado Weird, only package-lock.json changed?

**Comment by marcelomorgado** [comment]
> @marcelomorgado Weird, only package-lock.json changed?

Oh, I've forgotten this one, just done. Thanks

**Pull request merged**
